#!/bin/bash

jobs=(
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_1_nb_of_instances_50_time_limit_10_cluster1.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_2_nb_of_instances_50_time_limit_10_cluster1.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_3_nb_of_instances_50_time_limit_10_cluster1.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_4_nb_of_instances_50_time_limit_10_cluster1.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_5_nb_of_instances_50_time_limit_10_cluster1.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_6_nb_of_instances_50_time_limit_10_cluster1.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_7_nb_of_instances_50_time_limit_10_cluster1.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_8_nb_of_instances_50_time_limit_10_cluster1.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_9_nb_of_instances_50_time_limit_10_cluster1.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_10_nb_of_instances_50_time_limit_10_cluster1.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_1_nb_of_instances_50_time_limit_10_cluster2.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_2_nb_of_instances_50_time_limit_10_cluster2.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_3_nb_of_instances_50_time_limit_10_cluster2.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_4_nb_of_instances_50_time_limit_10_cluster2.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_5_nb_of_instances_50_time_limit_10_cluster2.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_6_nb_of_instances_50_time_limit_10_cluster2.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_7_nb_of_instances_50_time_limit_10_cluster2.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_8_nb_of_instances_50_time_limit_10_cluster2.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_9_nb_of_instances_50_time_limit_10_cluster2.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_10_nb_of_instances_50_time_limit_10_cluster2.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_1_nb_of_instances_50_time_limit_10_cluster3.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_2_nb_of_instances_50_time_limit_10_cluster3.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_3_nb_of_instances_50_time_limit_10_cluster3.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_4_nb_of_instances_50_time_limit_10_cluster3.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_5_nb_of_instances_50_time_limit_10_cluster3.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_6_nb_of_instances_50_time_limit_10_cluster3.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_7_nb_of_instances_50_time_limit_10_cluster3.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_8_nb_of_instances_50_time_limit_10_cluster3.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_9_nb_of_instances_50_time_limit_10_cluster3.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_10_nb_of_instances_50_time_limit_10_cluster3.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_1_nb_of_instances_50_time_limit_10_cluster4.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_2_nb_of_instances_50_time_limit_10_cluster4.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_3_nb_of_instances_50_time_limit_10_cluster4.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_4_nb_of_instances_50_time_limit_10_cluster4.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_5_nb_of_instances_50_time_limit_10_cluster4.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_6_nb_of_instances_50_time_limit_10_cluster4.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_7_nb_of_instances_50_time_limit_10_cluster4.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_8_nb_of_instances_50_time_limit_10_cluster4.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_9_nb_of_instances_50_time_limit_10_cluster4.sh"
    "search-strategy-generation-for-branch-and-bound-using-genetic-programming/batch_jobs/Gp_training_cluster/hc_complete/miplib_seed_10_nb_of_instances_50_time_limit_10_cluster4.sh"
)

for job in "${jobs[@]}"; do
    echo "Soumission de : $job"
     sbatch "$job"
done

echo "Tous les jobs ont été soumis via sbatch."
